# Generated by Django 2.0.1 on 2018-06-06 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('habitaciones', '0001_initial'),
        ('huespedes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ocupantes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_habitacion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habitaciones.Habitaciones')),
                ('id_huesped_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='huespedes.Huespedes')),
            ],
        ),
    ]
