# Generated by Django 2.0.1 on 2018-06-06 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('habitaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicia', models.DateField()),
                ('fecha_final', models.DateField()),
                ('costo_total', models.IntegerField(max_length=11)),
                ('reservaciones_id_habitacion', models.ManyToManyField(to='habitaciones.Habitaciones')),
            ],
        ),
    ]
