# Generated by Django 2.0.1 on 2018-06-06 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hoteles2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habitaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piso', models.IntegerField(max_length=11)),
                ('numero', models.IntegerField(max_length=11)),
                ('costo_x_dia', models.IntegerField(max_length=11)),
                ('capacidad', models.IntegerField(max_length=11)),
                ('id_hotel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoteles2.Hoteles')),
            ],
        ),
    ]
